# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MusicBrainz-Client
version:      0.11
version_from: Client.pm
installdirs:  site
requires:
    MusicBrainz::Queries:          0.10
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
